### ISSUE TITLE
Only shows the first 100 projects returned from the Azure.

### ISSUE THREAD

**Issue by sgtwilko** [expertasolutions/AzDo.VstsDashboard#158]
Our organisation has well over 100 projects.

The Default number of records returned by `getProjects` is 100.

This default can be overridden by providing a `top` value, I've tested the API and it will accept values up to at least 1,000.
(see [the API documentation](https://docs.microsoft.com/en-us/rest/api/azure/devops/core/projects/list?view=azure-devops-rest-6.0)  )

According to the [client documentation](https://docs.microsoft.com/en-us/javascript/api/azure-devops-extension-api/corerestclient#getprojects-any--number--number--string--boolean-) The `getProjects` `coreAPI` call should accept a `top` value.

How would you suggest we process so that we can use this on any of our projects?
Thanks

**Comment by lturmel** [comment]
Hi @sgtwilko, thanks for the proposition. Since the last year, I've stop enhancing this AzureDevOps extension, simply because I've move all my organization CICDPipeline into GitHub.

I will take a look at it, to improve it around your request, in order to let you see all your projects. My only fear here, is about the number of Pipelines that will came up if you decided to load all Pipelines of all Projects... After a while, you might hit the limits of request per mins allowed by Azure DevOps from you User Accounts which will slow down your usage :(

Let me check it during the next two or three weeks (I've a thigh schedule)...

In call case, let's keep in touch...

**Comment by lturmel** [comment]
@sgtwilko Fix has been made for you. You should be able to see all your projects with the new release.
ps; this is the last enhancement I made for this extension.
